// @flow

// leave off @2x/@3x
const images = {
    logo: require('../images/logoGreen.png'),
    back:require('../images/ic_back.png'),
    add:require('../images/ic_add.png'),
    login_bg:require('../images/login_bg.jpg'),
    login_logo:require('../images/login_logo.png'),
    home_community:require('../images/home_community_down.png'),
    home_maillist:require('../images/home_maillist_down.png'),
    home_news:require('../images/home_news_down.png'),
    home_patient:require('../images/home_patient_down.png'),
    about_us:require('../images/about_us.png'),
    change_phone:require('../images/change_phone.png'),
    change_psd:require('../images/change_psd.png'),
    donot_disturb:require('../images/donot_disturb.png'),
    layout:require('../images/layout.png'),
    persion_data:require('../images/persion_data.png'),
    leftnav_bg:require('../images/leftnav_bg.png'),
    default_hdimg:require('../images/default_hdimg.png'),
    default_msgimg:require('../images/default_msgimg.png'),
    code:require('../images/code.png'),
    message_focus:require('../images/message_focus.png'),
    patient_focus:require('../images/patient_focus.png'),
    community_focus:require('../images/community_focus.png'),
    address_list_focus:require('../images/address_list_focus.png'),
    already_finish_blue:require('../images/already_finish_blue.png'),
    already_finish_white:require('../images/already_finish_white.png'),
    change_already_phone_blue:require('../images/change_already_phone_blue.png'),
    change_already_phone_white:require('../images/change_already_phone_white.png'),
    verify_identity_blue:require('../images/verify_identity_blue.png'),
    verify_identity_white:require('../images/verify_identity_white.png'),
    Icon_Email:require('../images/Icon_Email.png'),
    Icon_Phone:require('../images/Icon_Phone.png'),
    confim_friend:require('../images/confim_friend.png'),
    search:require('../images/search.png'),
    add_new_friend:require('../images/add_new_friend.png'),
    erwei_code:require('../images/erwei_code.png'),
    erwei_zhuangshi:require('../images/erwei_zhuangshi.png'),
    not_checked:require('../images/not_checked.png'),
    checked:require('../images/checked.png'),
    voice:require('../images/voice.png'),
    delete:require('../images/delete.png'),
    delete_friend:require('../images/delete_friend.png'),
    send_my_card:require('../images/send_my_card.png'),
    send_msg:require('../images/send_msg.png'),
    add_friend:require('../images/add_friend.png'),
    packUp:require('../images/packUp.png'),
    unfold:require('../images/unfold.png'),
    management:require('../images/management.png'),
    add_member:require('../images/add_member.png'),
    add_friend_transparent:require('../images/add_friend_transparent.png'),
    scan:require('../images/scan.png'),
    message_default:require('../images/message_default.png'),
    adress_default:require('../images/adress_default.png'),
    community_default:require('../images/community_default.png'),
    launch_screen:require('../images/launch_screen.png'),
    checkbox_checked:require('../images/checkbox_checked.jpg'),
    checkbox_unchecked:require('../images/checkbox_unchecked.jpg'),
    checkbox_disabled:require('../images/checkbox_disabled.jpg'),
    clear_text:require('../images/clear_text.jpg'),
    nothing:require('../images/nothing.jpg'),
    more:require('../images/more.png'),
    startDiscussion:require('../images/startDiscussion.png'),
    error_image:require('../images/error_image.jpg'),
    line:require('../images/line.png'),
    transpond:require('../images/transpond.png'),
    affirm:require('../images/affirm.png'),
    publish:require('../images/publish.png'),
    view_member:require('../images/view_member.png'),
    view_result:require('../images/view_result.jpg'),
}

export default images
